# Copyright (c) 2021-2026 TiaC Systems
# SPDX-License-Identifier: Unlicense

name: Sync u-blox Project Forks

on:
  schedule: # At 02:00.
    - cron: '0 2 * * *'
  workflow_dispatch: # And manually on button click.

jobs:
  ublox-git-sync:
    name: Sync u-blox

    uses: tiacsys/github-workflows/.github/workflows/git-sync.yml@v2
    with:
      matrix: ./.github/git-sync-u-blox.yaml
      secret-prefix: "SSH_PRIVATE_KEY_"
    secrets: inherit # pass all secrets

  ublox-git-rebase:
    name: Rebase u-blox

    needs:
      - ublox-git-sync

    uses: tiacsys/github-workflows/.github/workflows/git-rebase.yml@v2
    with:
      matrix: ./.github/git-rebase-u-blox.yaml
      secret-prefix: "SSH_PRIVATE_KEY_"
      refspec-prefix: "tiacsys"
    secrets: inherit # pass all secrets

  ublox-git-rebase-itd:
    name: Rebase u-blox for ITD

    needs:
      - ublox-git-sync

    uses: tiacsys/github-workflows/.github/workflows/git-rebase.yml@v2
    with:
      matrix: ./.github/git-rebase-u-blox.yaml
      secret-prefix: "SSH_PRIVATE_KEY_"
      refspec-prefix: "itd"
    secrets: inherit # pass all secrets
