# Copyright (c) 2021-2025 TiaC Systems
# SPDX-License-Identifier: Unlicense

name: Sync Zephyr Project Forks

on:
  schedule: # At every minute past hour 0, 4, 8, 12, 16, and 20.
    - cron: '* 0,4,8,12,16,20 * * *'
  workflow_dispatch: # And manually on button click.

jobs:
  git-sync:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo:
          - zephyr
        branch:
          - collab-hwm
          - collab-init
          - collab-mesh-subnet
          - collab-rust
          - collab-safety
          - collab-sdk-dev
          - main
          - v4.2-branch
          - v4.1-branch
          - v4.0-branch
          - v3.7-branch
          - v3.6-branch
          - v3.5-branch
          - v3.4-branch
          - v3.3-branch
          - v3.2-branch
          - v3.1-branch
          - v3.0-branch
          - v2.7-auditable-branch
          - v2.7-branch
          - v2.6-branch
          - v2.5-branch
          - v2.4-branch
          - v2.3-branch
          - v2.2-branch
          - v2.1-branch
          - v2.0-branch
          - v1.14-branch
          - v1.13-branch
          - v1.12-branch
          - v1.11-branch
          - v1.10-branch
          - v1.9-branch
          - v1.8-branch
          - v1.7-branch
          - v1.6-branch
          - v1.5-branch
          - "refs/tags/*"

    steps:
      - name: git-sync-zephyr
        uses: tiacsys/git-sync@v3
        with:
          source_repo: "git@github.com:zephyrproject-rtos/${{ matrix.repo }}.git"
          source_branch: "${{ matrix.branch }}"
          destination_repo: "git@github.com:tiacsys/${{ matrix.repo }}.git"
          destination_branch: "${{ matrix.branch }}"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_ZEPHYR }}
        if: ${{ matrix.repo == 'zephyr' }}

  git-rebase:
    runs-on: ubuntu-latest

    needs: git-sync

    strategy:
      matrix:
        repo:
          - zephyr
        branch:
          - main
          - v4.2-branch
          - v4.1-branch
          - v4.0-branch
          - v3.7-branch
          - v3.6-branch
          - v3.5-branch
          - v3.4-branch
          - v3.3-branch
          - v3.2-branch
          - v3.1-branch
          - v3.0-branch
          - v2.7-branch
          - v2.6-branch
          - v2.5-branch

    steps:
      - name: git-rebase-zephyr
        uses: tiacsys/git-rebase@v1
        with:
          repo: "git@github.com:tiacsys/${{ matrix.repo }}.git"
          source_branch: "tiacsys/${{ matrix.branch }}"
          destination_branch: "${{ matrix.branch }}"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_ZEPHYR }}
        if: ${{ matrix.repo == 'zephyr' }}
