# Copyright (c) 2025-2026 TiaC Systems
# SPDX-License-Identifier: Unlicense

name: Sync CANnectivity Forks

on:
  schedule: # At minute 0 past every 4th hour.
    - cron: '0 */4 * * *'
  workflow_dispatch: # And manually on button click.

jobs:
  app-git-sync:
    name: Sync Application
    runs-on: ubuntu-latest

    strategy:
      matrix:
        org:
          - "${{ vars.BASE_URI_GH_TIACSYS_PRIVATE }}"
        repo:
          - cannectivity
        branch:
          - main
          - v1.3-branch
          - v1.2-branch
          - v1.1-branch
          - v1.0-branch
          - "refs/tags/*"

    steps:
      - name: Generate Secret String
        run: |
          varname_prefix="SSH_PRIVATE_KEY_"
          varname_unique="$(echo '${{ matrix.repo }}' | tr '[:punct:]' '_' | tr '[:lower:]' '[:upper:]')"
          varname_suffix=""
          varname=${varname_prefix}${varname_unique}${varname_suffix}
          echo "SECRET_STRING=${varname}" >> $GITHUB_ENV

      - name: Sync Git Refspecs
        uses: tiacsys/git-sync@v3
        with:
          source_repo: "${{ vars.BASE_URI_GH_CANNECTIVITY_PUBLIC }}/${{ matrix.repo }}.git"
          source_branch: "${{ matrix.branch }}"
          destination_repo: "${{ matrix.org }}/${{ matrix.repo }}.git"
          destination_branch: "${{ matrix.branch }}"
          ssh_private_key: "${{ secrets[env.SECRET_STRING] }}"

  app-git-rebase:
    name: Rebase Application
    runs-on: ubuntu-latest

    needs: app-git-sync

    strategy:
      matrix:
        org:
          - "${{ vars.BASE_URI_GH_TIACSYS_PRIVATE }}"
        repo:
          - cannectivity
        branch:
          - main
          - v1.3-branch
          - v1.2-branch
          - v1.1-branch
          - v1.0-branch

    steps:
      - name: Generate Secret String
        run: |
          varname_prefix="SSH_PRIVATE_KEY_"
          varname_unique="$(echo '${{ matrix.repo }}' | tr '[:punct:]' '_' | tr '[:lower:]' '[:upper:]')"
          varname_suffix=""
          varname=${varname_prefix}${varname_unique}${varname_suffix}
          echo "SECRET_STRING=${varname}" >> $GITHUB_ENV

      - name: Generate Prefix String
        run: |
          varname_prefix="GIT_REBASE_"
          varname_unique="$(echo '${{ matrix.org }}' | tr '[:punct:]' '_' | tr '[:lower:]' '[:upper:]')"
          varname_suffix="_BRANCH_PREFIX"
          varname=${varname_prefix}${varname_unique}${varname_suffix}
          echo "PREFIX_STRING=${varname}" >> $GITHUB_ENV

      - name: Rebase Custodians
        uses: tiacsys/git-rebase@v1
        with:
          repo: "${{ matrix.org }}/${{ matrix.repo }}.git"
          source_branch: "${{ vars[env.PREFIX_STRING] }}/${{ matrix.branch }}"
          destination_branch: "${{ matrix.branch }}"
          ssh_private_key: "${{ secrets[env.SECRET_STRING] }}"
