# Copyright (c) 2021-2026 TiaC Systems
# SPDX-License-Identifier: Unlicense

name: Sync Twister v2 Forks

on:
  schedule: # At 01:10.
    - cron: '10 1 * * *'
  workflow_dispatch: # And manually on button click.

jobs:
  twister2-git-sync:
    name: Sync Twister

    uses: tiacsys/github-workflows/.github/workflows/git-sync.yml@v2
    with:
      matrix: ./.github/git-sync-twister.yaml
      secret-prefix: "SSH_PRIVATE_KEY_"
      secret-suffix: "_V2"
    secrets: inherit # pass all secrets
