# Copyright (c) 2021-2026 TiaC Systems
# SPDX-License-Identifier: Unlicense

name: Sync OpenWCH SDK and HDK Forks

on:
  schedule: # At minute 45 past every 4th hour.
    - cron: '45 */4 * * *'
  workflow_dispatch: # And manually on button click.

jobs:
  openwch-git-sync:
    name: Sync OpenWCH
    runs-on: ubuntu-latest

    strategy:
      matrix:
        org:
          - "${{ vars.BASE_URI_GH_TIACSYS_PRIVATE }}"
        repo:
          - ch32f20x
          - ch32l103
          - ch32m030
          - ch32v002_004_005_006_007
          - ch32v003
          - ch32v103
          - ch32v20x
          - ch32v307
          - ch32x035
          - ch569
          - ch570
          - ch583
          - ch585
          - ch592
          - ch641
          - ch643
        branch:
          - "refs/heads/*"
          - "refs/tags/*"

    steps:
      - name: Generate Secret String
        run: |
          varname_prefix="SSH_PRIVATE_KEY_"
          varname_unique="$(echo '${{ matrix.repo }}' | tr '[:punct:]' '_' | tr '[:lower:]' '[:upper:]')"
          varname_suffix=""
          varname=${varname_prefix}${varname_unique}${varname_suffix}
          echo "SECRET_STRING=${varname}" >> $GITHUB_ENV

      - name: Sync Git Refspecs
        uses: tiacsys/git-sync@v3
        with:
          source_repo: "${{ vars.BASE_URI_GH_OPENWCH_PUBLIC }}/${{ matrix.repo }}.git"
          source_branch: "${{ matrix.branch }}"
          destination_repo: "${{ matrix.org }}/openwch-${{ matrix.repo }}.git"
          destination_branch: "${{ matrix.branch }}"
          ssh_private_key: "${{ secrets[env.SECRET_STRING] }}"
