# Copyright (c) 2021-2026 TiaC Systems
# SPDX-License-Identifier: Unlicense

name: Sync Lua Project Forks

on:
  schedule: # At 01:35.
    - cron: '35 1 * * *'
  workflow_dispatch: # And manually on button click.

jobs:
  lua-git-sync:
    name: Sync LUA

    uses: tiacsys/github-workflows/.github/workflows/git-sync.yml@v2
    with:
      matrix: ./.github/git-sync-lua.yaml
      secret-prefix: "SSH_PRIVATE_KEY_"
    secrets: inherit # pass all secrets
