# Copyright (c) 2021-2026 TiaC Systems
# SPDX-License-Identifier: Unlicense

name: Sync Twister v2 Forks

on:
  schedule: # At 01:10.
    - cron: '10 1 * * *'
  workflow_dispatch: # And manually on button click.

jobs:
  twister2-git-sync:
    name: Sync Twister
    runs-on: ubuntu-latest

    strategy:
      matrix:
        org:
          - "${{ vars.BASE_URI_GH_TIACSYS_PRIVATE }}"
        repo:
          - twister
        branch:
          - "refs/heads/*"
          - "refs/tags/*"

    steps:
      - name: Generate Secret String
        run: |
          varname_prefix="SSH_PRIVATE_KEY_"
          varname_unique="$(echo '${{ matrix.repo }}' | tr '[:punct:]' '_' | tr '[:lower:]' '[:upper:]')"
          varname_suffix="_V2"
          varname=${varname_prefix}${varname_unique}${varname_suffix}
          echo "SECRET_STRING=${varname}" >> $GITHUB_ENV

      - name: Sync Git Refspecs
        uses: tiacsys/git-sync@v3
        with:
          source_repo: "${{ vars.BASE_URI_GH_ZEPHYR_PROJECT_PUBLIC }}/${{ matrix.repo }}.git"
          source_branch: "${{ matrix.branch }}"
          destination_repo: "${{ matrix.org }}/${{ matrix.repo }}.git"
          destination_branch: "${{ matrix.branch }}"
          ssh_private_key: "${{ secrets[env.SECRET_STRING] }}"
