# Copyright (c) 2021 TiaC Systems
# SPDX-License-Identifier: Apache-2.0

name: Sync Zephyr Project Forks

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
  workflow_dispatch: # on button click

jobs:
  git-sync:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo:
          - zephyr
        branch:
          - main
          - v2.6-branch
          - v2.5-branch
          - v2.4-branch
          - v2.3-branch
          - v2.2-branch
          - v2.1-branch
          - v2.0-branch
          - v1.14-branch
          - v1.13-branch
          - v1.12-branch
          - v1.11-branch
          - v1.10-branch
          - v1.9-branch
          - v1.8-branch
          - v1.7-branch
          - v1.6-branch
          - v1.5-branch

    steps:
      - name: key-setup
        run: |
          if [[ ${{ matrix.repo }} == kicad-symbols ]]; then
            echo "SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY_ZEPHYR }}" >> $GITHUB_ENV
          else
            echo "SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
          fi

      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:zephyrproject-rtos/${{ matrix.repo }}.git"
          source_branch: "${{ matrix.branch }}"
          destination_repo: "git@github.com:tiacsys/${{ matrix.repo }}.git"
          destination_branch: "${{ matrix.branch }}"
          ssh_private_key: ${{ env.SSH_PRIVATE_KEY }}
