# Copyright (c) 2021-2026 TiaC Systems
# SPDX-License-Identifier: Unlicense

name: Sync OpenWCH SDK and HDK Forks

on:
  schedule: # At minute 45 past every 4th hour.
    - cron: '45 */4 * * *'
  workflow_dispatch: # And manually on button click.

jobs:
  openwch-git-sync:
    name: Sync OpenWCH

    uses: tiacsys/github-workflows/.github/workflows/git-sync.yml@v2
    with:
      matrix: ./.github/git-sync-openwch.yaml
      secret-prefix: "SSH_PRIVATE_KEY_"
      to-repo-prefix: "openwch-"
    secrets: inherit # pass all secrets
