# Copyright (c) 2021-2026 TiaC Systems
# SPDX-License-Identifier: Unlicense

name: Sync ADI Trinamic Forks

on:
  schedule: # At 03:00.
    - cron: '0 3 * * *'
  workflow_dispatch: # And manually on button click.

jobs:
  tmc-git-sync:
    name: Sync Trinamic

    uses: tiacsys/github-workflows/.github/workflows/git-sync.yml@v2
    with:
      matrix: ./.github/git-sync-aditmc.yaml
      secret-prefix: "SSH_PRIVATE_KEY_"
    secrets: inherit # pass all secrets
