# Copyright (c) 2021 TiaC Systems
# SPDX-License-Identifier: Apache-2.0

name: Sync Zephyr Fork

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
  workflow_dispatch: # on button click

jobs:
  git-sync:
    runs-on: ubuntu-latest

    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:zephyrproject-rtos/zephyr.git"
          source_branch: "main"
          destination_repo: "git@github.com:tiacsys/zephyr.git"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
