# Copyright (c) 2021-2026 TiaC Systems
# SPDX-License-Identifier: Unlicense

name: Sync Zephyr Project Forks

on:
  schedule: # At minute 0 past every 4th hour.
    - cron: '0 */4 * * *'
  workflow_dispatch: # And manually on button click.

jobs:
  zephyr-git-sync:
    name: Sync Zephyr

    uses: tiacsys/github-workflows/.github/workflows/git-sync.yml@v2
    with:
      matrix: ./.github/git-sync-zephyr.yaml
      secret-prefix: "SSH_PRIVATE_KEY_"
    secrets: inherit # pass all secrets

  zephyr-git-rebase:
    name: Rebase Zephyr

    needs:
      - zephyr-git-sync

    uses: tiacsys/github-workflows/.github/workflows/git-rebase.yml@v2
    with:
      matrix: ./.github/git-rebase-zephyr.yaml
      secret-prefix: "SSH_PRIVATE_KEY_"
      refspec-prefix: "tiacsys"
    secrets: inherit # pass all secrets
