# Copyright (c) 2021-2026 TiaC Systems
# SPDX-License-Identifier: Unlicense

name: Sync NASA Software V&V Forks

on:
  schedule: # At 01:30.
    - cron: '30 1 * * *'
  workflow_dispatch: # And manually on button click.

jobs:
  nasa-git-sync:
    name: Sync NASA

    uses: tiacsys/github-workflows/.github/workflows/git-sync.yml@v2
    with:
      matrix: ./.github/git-sync-nasa.yaml
      secret-prefix: "SSH_PRIVATE_KEY_"
    secrets: inherit # pass all secrets
