# Copyright (c) 2021-2026 TiaC Systems
# SPDX-License-Identifier: Unlicense

name: Sync Melexis OS Team Forks

on:
  schedule: # At 01:15.
    - cron: '15 1 * * *'
  workflow_dispatch: # And manually on button click.

jobs:
  melexis-git-sync:
    name: Sync Melexis

    uses: tiacsys/github-workflows/.github/workflows/git-sync.yml@v2
    with:
      matrix: ./.github/git-sync-melexis.yaml
      secret-prefix: "SSH_PRIVATE_KEY_"
    secrets: inherit # pass all secrets

  melexis-git-rebase:
    name: Rebase Melexis

    needs:
      - melexis-git-sync

    uses: tiacsys/github-workflows/.github/workflows/git-rebase.yml@v2
    with:
      matrix: ./.github/git-rebase-melexis.yaml
      secret-prefix: "SSH_PRIVATE_KEY_"
      refspec-prefix: "tiacsys"
    secrets: inherit # pass all secrets
