# Copyright (c) 2021-2026 TiaC Systems
# SPDX-License-Identifier: Unlicense

name: Sync Tooling Forks

on:
  schedule: # At 01:00.
    - cron: '0 1 * * *'
  workflow_dispatch: # And manually on button click.

jobs:
  zephyr-gha-git-sync:
    name: Sync Zephyr GitHub Actions

    uses: tiacsys/github-workflows/.github/workflows/git-sync.yml@v2
    with:
      matrix: ./.github/git-sync-tooling-zephyr-gha.yaml
      secret-prefix: "SSH_PRIVATE_KEY_TOOLING_"
      from-repo-prefix: "action-"
    secrets: inherit # pass all secrets

  siemens-git-sync:
    name: Sync Siemens

    uses: tiacsys/github-workflows/.github/workflows/git-sync.yml@v2
    with:
      matrix: ./.github/git-sync-tooling-siemens.yaml
      secret-prefix: "SSH_PRIVATE_KEY_TOOLING_"
    secrets: inherit # pass all secrets

  wei-git-sync:
    name: Sync Wei He

    uses: tiacsys/github-workflows/.github/workflows/git-sync.yml@v2
    with:
      matrix: ./.github/git-sync-tooling-wei.yaml
      secret-prefix: "SSH_PRIVATE_KEY_TOOLING_"
    secrets: inherit # pass all secrets

  mrsquaare-gha-git-sync:
    name: Sync Guillaume Bonnet GitHub Actions

    uses: tiacsys/github-workflows/.github/workflows/git-sync.yml@v2
    with:
      matrix: ./.github/git-sync-tooling-mrsquaare-gha.yaml
      secret-prefix: "SSH_PRIVATE_KEY_TOOLING_"
      from-repo-suffix: "-action"
    secrets: inherit # pass all secrets
