# Copyright (c) 2021-2026 TiaC Systems
# SPDX-License-Identifier: Unlicense

name: Sync Tooling Forks

on:
  schedule: # At 01:00.
    - cron: '0 1 * * *'
  workflow_dispatch: # And manually on button click.

jobs:
  zephyr-gha-git-sync:
    name: Sync Zephyr GitHub Actions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        org:
          - "${{ vars.BASE_URI_GH_TIACSYS_PRIVATE }}"
        repo:
          - zephyr-setup
        branch:
          - "refs/heads/*"
          - "refs/tags/*"

    steps:
      - name: Generate Secret String
        run: |
          varname_prefix="SSH_PRIVATE_KEY_TOOLING_"
          varname_unique="$(echo '${{ matrix.repo }}' | tr '[:punct:]' '_' | tr '[:lower:]' '[:upper:]')"
          varname_suffix=""
          varname=${varname_prefix}${varname_unique}${varname_suffix}
          echo "SECRET_STRING=${varname}" >> $GITHUB_ENV

      - name: Sync Git Refspecs
        uses: tiacsys/git-sync@v3
        with:
          source_repo: "${{ vars.BASE_URI_GH_ZEPHYR_PROJECT_PUBLIC }}/action-${{ matrix.repo }}.git"
          source_branch: "${{ matrix.branch }}"
          destination_repo: "${{ matrix.org }}/${{ matrix.repo }}.git"
          destination_branch: "${{ matrix.branch }}"
          ssh_private_key: "${{ secrets[env.SECRET_STRING] }}"

  siemens-git-sync:
    name: Sync Siemens
    runs-on: ubuntu-latest

    strategy:
      matrix:
        org:
          - "${{ vars.BASE_URI_GH_TIACSYS_PRIVATE }}"
        repo:
          - kas
        branch:
          - "refs/heads/*"
          - "refs/tags/*"

    steps:
      - name: Generate Secret String
        run: |
          varname_prefix="SSH_PRIVATE_KEY_TOOLING_"
          varname_unique="$(echo '${{ matrix.repo }}' | tr '[:punct:]' '_' | tr '[:lower:]' '[:upper:]')"
          varname_suffix=""
          varname=${varname_prefix}${varname_unique}${varname_suffix}
          echo "SECRET_STRING=${varname}" >> $GITHUB_ENV

      - name: Sync Git Refspecs
        uses: tiacsys/git-sync@v3
        with:
          source_repo: "${{ vars.BASE_URI_GH_SIEMENS_PUBLIC }}/${{ matrix.repo }}.git"
          source_branch: "${{ matrix.branch }}"
          destination_repo: "${{ matrix.org }}/${{ matrix.repo }}.git"
          destination_branch: "${{ matrix.branch }}"
          ssh_private_key: "${{ secrets[env.SECRET_STRING] }}"

  wei-git-sync:
    name: Sync Wei He
    runs-on: ubuntu-latest

    strategy:
      matrix:
        org:
          - "${{ vars.BASE_URI_GH_TIACSYS_PRIVATE }}"
        repo:
          - git-sync
        branch:
          - "refs/heads/*"
          - "refs/tags/*"

    steps:
      - name: Generate Secret String
        run: |
          varname_prefix="SSH_PRIVATE_KEY_TOOLING_"
          varname_unique="$(echo '${{ matrix.repo }}' | tr '[:punct:]' '_' | tr '[:lower:]' '[:upper:]')"
          varname_suffix=""
          varname=${varname_prefix}${varname_unique}${varname_suffix}
          echo "SECRET_STRING=${varname}" >> $GITHUB_ENV

      - name: Sync Git Refspecs
        uses: tiacsys/git-sync@v3
        with:
          source_repo: "${{ vars.BASE_URI_GH_WEI_PUBLIC }}/${{ matrix.repo }}.git"
          source_branch: "${{ matrix.branch }}"
          destination_repo: "${{ matrix.org }}/${{ matrix.repo }}.git"
          destination_branch: "${{ matrix.branch }}"
          ssh_private_key: "${{ secrets[env.SECRET_STRING] }}"

  mrsquaare-gha-git-sync:
    name: Sync Guillaume Bonnet GitHub Actions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        org:
          - "${{ vars.BASE_URI_GH_TIACSYS_PRIVATE }}"
        repo:
          - ssh-setup
        branch:
          - "refs/heads/*"
          - "refs/tags/*"

    steps:
      - name: Generate Secret String
        run: |
          varname_prefix="SSH_PRIVATE_KEY_TOOLING_"
          varname_unique="$(echo '${{ matrix.repo }}' | tr '[:punct:]' '_' | tr '[:lower:]' '[:upper:]')"
          varname_suffix=""
          varname=${varname_prefix}${varname_unique}${varname_suffix}
          echo "SECRET_STRING=${varname}" >> $GITHUB_ENV

      - name: Sync Git Refspecs
        uses: tiacsys/git-sync@v3
        with:
          source_repo: "${{ vars.BASE_URI_GH_MRSQUAARE_PUBLIC }}/${{ matrix.repo }}-action.git"
          source_branch: "${{ matrix.branch }}"
          destination_repo: "${{ matrix.org }}/${{ matrix.repo }}.git"
          destination_branch: "${{ matrix.branch }}"
          ssh_private_key: "${{ secrets[env.SECRET_STRING] }}"
