# Copyright (c) 2021-2022 TiaC Systems
# SPDX-License-Identifier: Unlicense

name: Sync Lua Project Forks

on:
  schedule: # At every minute past hour 0, 4, 8, 12, 16, and 20.
    - cron: '* 0,4,8,12,16,20 * * *'
  workflow_dispatch: # And manually on button click.

jobs:
  git-sync:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo:
          - lua
        branch:
          - master
          - "refs/heads/v5.4.0"
          - "refs/heads/v5.4"
          - "refs/heads/v5.3"
          - "refs/heads/v5-2"
          - "refs/tags/*"

    steps:
      - name: git-sync-lua
        uses: tiacsys/git-sync@v3
        with:
          source_repo: "git@github.com:lua/${{ matrix.repo }}.git"
          source_branch: "${{ matrix.branch }}"
          destination_repo: "git@github.com:tiacsys/${{ matrix.repo }}.git"
          destination_branch: "${{ matrix.branch }}"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_LUA }}
        if: ${{ matrix.repo == 'lua' }}
