# Copyright (c) 2021-2026 TiaC Systems
# SPDX-License-Identifier: Unlicense

name: Sync Quantum Leaps Project Forks

on:
  schedule: # At 01:25.
    - cron: '25 1 * * *'
  workflow_dispatch: # And manually on button click.

jobs:
  ql-git-sync:
    name: Sync Quantum Leaps

    uses: tiacsys/github-workflows/.github/workflows/git-sync.yml@v2
    with:
      matrix: ./.github/git-sync-ql.yaml
      secret-prefix: "SSH_PRIVATE_KEY_"
    secrets: inherit # pass all secrets
